<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class Res_CreateCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('food_groups')->insert([
            [
                "persian_name"=>"پیتزا آمریکایی",
                "english_name"=>"americanPizza",
                "logo"=>"pizza",
                "status"=>"active",
                "res_english_name"=>"cuki",
                "average_color"=>"#A89457",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"ایرانی",
                "english_name"=>"irani",
                "logo"=>"irani",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"#70907B",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"برگر",
                "english_name"=>"burger",
                "logo"=>"burger",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"#E07F4C",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"پاستا",
                "english_name"=>"pasta",
                "logo"=>"pasta",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"#70907B",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"پنینی",
                "english_name"=>"panini",
                "logo"=>"panini",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"#E07F4C",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"پیتزا",
                "english_name"=>"pizza",
                "logo"=>"pizza",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"#A89457",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"ساندویچ",
                "english_name"=>"sandwich",
                "logo"=>"sandwich",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"#933939",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"غذای دریای",
                "english_name"=>"seaFoods",
                "logo"=>"seaFoods",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"#71917B",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"استیک",
                "english_name"=>"steak",
                "logo"=>"steak",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"#BC4040",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"پیتزا ایتالیایی",
                "english_name"=>"italianPizza",
                "logo"=>"pizza",
                "status"=>"active",
                "res_english_name"=>"cuki",
                "average_color"=>"#A89457",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"مرغ",
                "english_name"=>"chicken",
                "logo"=>"chicken",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"#E07F4C",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"پیش غذا",
                "english_name"=>"appetizer",
                "logo"=>"appetizer",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"#70907B",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"سالاد",
                "english_name"=>"salad",
                "logo"=>"salad",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"#929292",
                "type"=>"restaurant"
            ],
            [
                "persian_name"=>"کیک",
                "english_name"=>"cake",
                "logo"=>"cake",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"",
                "type"=>"coffeeshop"
            ],
            [
                "persian_name"=>"قهوه",
                "english_name"=>"coffee",
                "logo"=>"coffee",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"",
                "type"=>"coffeeshop"
            ],
            [
                "persian_name"=>"دمنوش",
                "english_name"=>"hearbalTea",
                "logo"=>"hearbalTea",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"",
                "type"=>"coffeeshop"
            ],
            [
                "persian_name"=>"بستنی",
                "english_name"=>"iceCream",
                "logo"=>"iceCream",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"",
                "type"=>"coffeeshop"
            ],
            [
                "persian_name"=>"آبمیوه",
                "english_name"=>"juice",
                "logo"=>"juice",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"",
                "type"=>"coffeeshop"
            ],
            [
                "persian_name"=>"شیک",
                "english_name"=>"shake",
                "logo"=>"shake",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"",
                "type"=>"coffeeshop"
            ],
            [
                "persian_name"=>"اسموتی",
                "english_name"=>"smoothie",
                "logo"=>"smoothie",
                "status"=>"active",
                "res_english_name"=>"general",
                "average_color"=>"",
                "type"=>"coffeeshop"
            ]
        ]);

    }
}
